[package]
name = "yksom"
version = "0.1.0"
authors = ["Laurence Tratt <laurie@tratt.net>"]
edition = "2018"

[[bin]]
doc = false
name = "yksom"

[lib]
name = "yksom"
path = "src/lib/mod.rs"

[[test]]
name = "lang_tests"
path = "lang_tests/run.rs"
harness = false

[build-dependencies]
cfgrammar = "0.4"
lrlex = "0.4"
lrpar = "0.4"
rerun_except = "0.1"

[dev-dependencies]
lang_tester = "0.2"
lazy_static = "1.3"
regex = "1.1"

[dependencies]
cfgrammar = "0.4"
enum-primitive-derive = "0.1"
getopts = "0.2"
indexmap = "1.0"
itertools = "0.8"
lrlex = "0.4"
lrpar = "0.4"
num-traits = "0.2"
