[package]
name = "yksom"
version = "0.1.0"
authors = ["Laurence Tratt <laurie@tratt.net>"]
edition = "2018"

[[bin]]
doc = false
name = "yksom"

[lib]
name = "yksom"
path = "src/lib/mod.rs"

[build-dependencies]
cfgrammar = "0.3"
lrlex = "0.3"
lrpar = "0.3"

[dependencies]
cfgrammar = "0.3"
enum-primitive-derive = "0.1"
getopts = "0.2"
indexmap = "1.0"
itertools = "0.8"
lrlex = "0.3"
lrpar = "0.3"
num-traits = "0.2"
